nudge_creation_api/nudge_creation_api/urls.py
from django.conf import settings
from django.conf.urls.static import static



from django.contrib import admin
from django.urls import path

from nudges.views import (
    welcome_screen_view, add_event_view,add_event,all_events,delete_event,event,
    )

urlpatterns = [
    path("admin/", admin.site.urls),
    path('',welcome_screen_view,name='welcome'),
    path('events/',add_event_view,name="add_event_view"),
    path('add_event',add_event,name="add_event"),
    path('all_events/', all_events,name="all_events"),
    path('delete_event/<int:event>/',delete_event,name='delete_event'),
    path('event', event,name="search_event"),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

nudge_creation_api/nudges/models.py
from django.db import models
import uuid

# Create your models here.

class nudge_model(models.Model):
    uid = models.UUIDField(default=uuid.uuid4, editable=False)
    name = models.CharField(max_length=100)
    image = models.ImageField(upload_to='nudge_images/', null=True, blank=True)
    tagline = models.CharField(max_length=100)
    schedule = models.DateTimeField()
    description = models.TextField()
    moderator = models.CharField(max_length=100)
    category = models.CharField(max_length=100)
    sub_category = models.CharField(max_length=100)
    rigor_rank = models.IntegerField()

nudge_creation_api/nudges/forms.py
from django import forms
from .models import nudge_model

class nudge_form(forms.ModelForm):
    class Meta:
        model = nudge_model
        fields = ['name', 'image', 'tagline', 'schedule', 'description', 'moderator', 'category', 'sub_category', 'rigor_rank']
        widgets = {
            'image': forms.FileInput(attrs={'accept': 'image/*'}),  # Restrict file selection to images
        }

nudge_creation_api/nudges/views.py
from django.shortcuts import render
from django.views.decorators.csrf import csrf_protect
from django.shortcuts import render, redirect

from .forms import nudge_form
from .models import nudge_model
import uuid
def welcome_screen_view(request):
	print(request.headers)
	return render(request,"nudges/welcome.html",{})

def add_event_view(request):
	print(request.headers)
	return render(request,"nudges/create_event.html",{})


from django.core.paginator import Paginator

def all_events(request):
    events = nudge_model.objects.all()
    paginator = Paginator(events, 2)  

    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    return render(request, "nudges/all_events.html", {'page_obj': page_obj})




@csrf_protect
def add_event(request):
	if request.method == 'POST':
		form = nudge_form(request.POST, request.FILES)
		if form.is_valid():
			uid = str(uuid.uuid4())
			name = form.cleaned_data[ 'name']
			image = form.cleaned_data['image']
			tagline = form.cleaned_data['tagline']
			schedule = form.cleaned_data['schedule']
			description = form.cleaned_data['description']
			moderator = form.cleaned_data['moderator']
			category = form.cleaned_data['category']
			sub_category = form.cleaned_data['sub_category']
			rigor_rank = form.cleaned_data['rigor_rank']

			nudge_model = form.save(commit=False)
			nudge_model.uid = uid
			nudge_model.save()
			# return render(request, 'account/tempview.html', {'classes': classes})
			return redirect('all_events')
		else:
			form = add_class_form(request.POST)
			print(form.errors)
			return redirect('add_event_view')
	else:
		form = add_class_form()
	return render(request, 'nudges/add_event.html', {'form': form})



def delete_event(request,event):
	event_to_delete = nudge_model.objects.get(pk=event)
	event_to_delete.delete()
	return redirect('all_events')



def event(request):
    if 'uuid' in request.GET:
        uuid = request.GET['uuid']
        try:
            event = nudge_model.objects.get(uid=uuid)
            return render(request, 'nudges/search_result.html', {'event': event})
        except nudge_model.DoesNotExist:
            return render(request, 'nudges/search_result.html', {'event': None})

    return render(request, 'nudges/search_event.html')

nudge_creation_api/nudges/templates/nudges/all_events.html
{% extends 'base.html' %}

{% block content %}

<form action="{% url 'search_event' %}" method="get">
    {% csrf_token %}
  <input type="text" name="uuid" placeholder="Enter UUID">
  <button type="submit">Search</button>
</form>

{% if page_obj %}

{% for event in page_obj %}
  <h1>{{ event.name }}</h1>
  <img src="{{ event.image.url }}" alt="Event Image" width="100" height="100">
  <h2>{{ event.uid }}</h2>
  <a href="{% url 'delete_event' event.id %}" method="post">
    <button>Delete</button>
  </a>
{% endfor %}
<br>
<br>
<br>
<a href="{% url 'add_event_view' %}">
    <button>Create new event</button>
</a>

<br>
<br>
<div class="pagination">
    <span class="step-links">
        {% if page_obj.has_previous %}
            <a href="?page=1">&laquo; first</a>
            <a href="?page={{ page_obj.previous_page_number }}">previous</a>
        {% endif %}

        <span class="current-page">current page {{ page_obj.number }}</span>

        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">next</a>
            <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
        {% endif %}
    </span>
</div>

{% else %}

<h1>No events</h1>

{% endif %}

{% endblock %}

nudge_creation_api/nudges/templates/nudges/create_event.html
{% extends 'base.html' %}


{% block content %}


<form method="POST" enctype="multipart/form-data" action="{% url 'add_event' %}">
  {% csrf_token %}
  <div>
    <label for="id_name">Name:</label>
    <input type="text" id="id_name" name="name" required>
  </div>
  <div>
    <label for="id_image">Image:</label>
    <input type="file" id="id_image" name="image" accept="image/*">
  </div>
  <div>
    <label for="id_tagline">Tagline:</label>
    <input type="text" id="id_tagline" name="tagline" required>
  </div>
  <div>
    <label for="id_schedule">Schedule:</label>
    <input type="datetime-local" id="id_schedule" name="schedule" required>
  </div>
  <div>
    <label for="id_description">Description:</label>
    <textarea id="id_description" name="description" required></textarea>
  </div>
  <div>
    <label for="id_moderator">Moderator:</label>
    <input type="text" id="id_moderator" name="moderator" required>
  </div>
  <div>
    <label for="id_category">Category:</label>
    <input type="text" id="id_category" name="category" required>
  </div>
  <div>
    <label for="id_sub_category">Sub Category:</label>
    <input type="text" id="id_sub_category" name="sub_category" required>
  </div>
  <div>
    <label for="id_rigor_rank">Rigor Rank:</label>
    <input type="number" id="id_rigor_rank" name="rigor_rank" required>
  </div>

  <input type="submit" placeholder="Submit">
</form>


{% endblock content %}

nudge_creation_api/nudges/templates/nudges/search_result.html
{% extends 'base.html' %}

{% block content %}


{% if event %}

  <h1>{{ event.name }}</h1>
  <img src="{{ event.image.url }}" alt="Event Image" width="100" height="100">
  <h2>{{ event.uid }}</h2>
  <a href="{% url 'delete_event' event.id %}" method="post">
    <button>Delete</button>
  </a>

{% else %}

<h1>No events</h1>

{% endif %}

{% endblock %}

nudge_creation_api/nudges/templates/nudges/welcome.html
{% extends 'base.html' %}


{% block content %}

<h1>Welcome</h1>
<a href="{% url 'add_event_view' %}">
	<button>Create Event</button>
</a>
<br>
<br>
<br>


<a href="{% url 'all_events' %}">
	<button>View Events</button>
</a>

{% endblock content %}

nudge_creation_api/templates/base.html
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>Nudges</title>
	{% load static %}
	<link rel="stylesheet" href="{% static 'nudges/create_event.css' %}">

</head>
<body>

	{% block content %}

	{% endblock content %}

</body>
</html>